#!/usr/bin/env php
<?php

declare(strict_types=1);

use TBoileau\PhpCodePolicyEnforcer\Cli\Application;

$composerAutoloadPath = null;

if (isset($GLOBALS['_composer_autoload_path']) && file_exists($GLOBALS['_composer_autoload_path'])) {
    $composerAutoloadPath = $GLOBALS['_composer_autoload_path'];
} else {
    foreach (array(__DIR__ . '/../../../autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
        if (file_exists($file)) {
            $composerAutoloadPath = $file;
            break;
        }
    }
}

if (null === $composerAutoloadPath) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require $composerAutoloadPath;

(new Application())->run();
